title: Jekyll-Bootstrap-GitHub Pages site demo
url: https://mangkoran.github.io/jekyll-bootstrap-demo-v2

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer

sass:
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.org"
