title: Jekyll-Bootstrap-GitHub Pages site demo

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer

sass:
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock

exclude_patterns:
  - "*.org"
